import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'th' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  th: {
    // App Brand & Topbar
    appName: 'NetMonitor',
    appSub: 'ระบบตรวจวัดและบริหารจัดการอุปกรณ์เครือข่ายและจุดกระจายสัญญาณไร้สาย',
    coreGateway: 'เกตเวย์หลัก',
    gatewayOnline: 'ออนไลน์',
    pingLatency: 'ความหน่วง',
    searchPlaceholder: 'ค้นหา อุปกรณ์, IP, MAC, VLAN หรือ SSID...',
    profile: 'โปรไฟล์',
    role: 'บทบาท',
    logout: 'ออกจากระบบ',
    switchRole: 'สลับสิทธิ์ทดสอบ',
    notifications: 'การแจ้งเตือนระบบ',
    noAlerts: 'ไม่มีการแจ้งเตือนค้างอยู่',
    viewAllAlerts: 'ดูการแจ้งเตือนทั้งหมด',

    // Roles
    roleAdmin: 'ผู้ดูแลระบบ (Admin)',
    roleEngineer: 'วิศวกรระบบ (Engineer)',
    roleViewer: 'ผู้สังเกตการณ์ (Viewer - อ่านอย่างเดียว)',

    // Navigation Menu
    navDashboard: 'แดชบอร์ดภาพรวม',
    navDevices: 'คลังอุปกรณ์เครือข่าย',
    navPorts: 'เมทริกซ์พอร์ตสวิตช์',
    navVlans: 'วิเคราะห์ทราฟฟิก VLAN',
    navAPs: 'จุดกระจายสัญญาณไร้สาย',
    navClients: 'เซสชันอุปกรณ์ลูกข่าย',
    navTopology: 'แผนผังเครือข่ายแบบโต้ตอบ',
    navAlerts: 'แจ้งเตือนเหตุการณ์ผิดปกติ',
    navEventLogs: 'บันทึกเหตุการณ์ (Syslog)',
    navStatistics: 'สถิติการใช้งานแบนด์วิดท์',
    navUsers: 'จัดการผู้ใช้งานและสิทธิ์',
    navSettings: 'ตั้งค่าระบบ',

    // Dashboard
    totalHardware: 'อุปกรณ์ฮาร์ดแวร์ทั้งหมด',
    activeNodes: 'โหนดที่ทำงานปกติ',
    disconnectedNodes: 'โหนดมีปัญหา/ตัดการเชื่อมต่อ',
    broadcastingAPs: 'จุด AP ที่กระจายสัญญาณ',
    activeClients: 'ไคลเอนต์ที่กำลังเชื่อมต่อ',
    totalThroughput: 'อัตราส่งผ่านข้อมูลรวม',
    telemetryTitle: 'การรับส่งข้อมูลแบบเรียลไทม์ (Mbps)',
    cpuMemoryTitle: 'การใช้พลังงาน CPU & RAM เฉลี่ยทั้งระบบ',
    topVlansTitle: 'ปริมาณการใช้งานทราฟฟิกแยกตาม VLAN',
    topologyPreview: 'พรีวิวแผนผังโทโพโลยี',
    viewFullTopology: 'เปิดแผนผังแบบเต็มหน้าจอ',
    criticalIncidents: 'เหตุการณ์วิกฤตที่ต้องตรวจสอบ',
    systemHealth: 'ดัชนีสุขภาพระบบ',
    nominalStatus: 'การทำงานอยู่ในเกณฑ์เสถียร',
    lastSyncTime: 'อัปเดตข้อมูลล่าสุดเมื่อ',
    refreshData: 'รีเฟรชข้อมูล',

    // Devices
    devicesInventory: 'คลังอุปกรณ์เครือข่ายทั้งหมด',
    addDevice: '+ เพิ่มอุปกรณ์ใหม่',
    deviceTypeFilter: 'ประเภทอุปกรณ์',
    statusFilter: 'สถานะ',
    allTypes: 'ทุกประเภท',
    allStatuses: 'ทุกสถานะ',
    deviceName: 'ชื่ออุปกรณ์',
    ipAddress: 'IP Address',
    type: 'ประเภท',
    modelVendor: 'รุ่น / แบรนด์',
    locationRack: 'สถานที่ติดตั้ง / ตู้แร็ค',
    uptime: 'ระยะเวลาทำงาน',
    cpuRam: 'การใช้ CPU / RAM',
    portsUp: 'พอร์ต UP / ทั้งหมด',
    actions: 'การจัดการ',
    inspectPorts: 'ดูพอร์ต',
    importConfig: 'อิมพอร์ต Config',
    editDevice: 'แก้ไข',
    deleteDevice: 'ลบ',
    readOnlyNotice: 'โหมดอ่านอย่างเดียว: ไม่สามารถแก้ไขหรือลบอุปกรณ์ได้',

    // Ports
    switchPortMatrix: 'เมทริกซ์สถานะพอร์ตสวิตช์กายภาพ',
    selectSwitch: 'เลือกสวิตช์เพื่อตรวจสอบ:',
    portStatusLegend: 'คำอธิบายสีพอร์ต:',
    portUp: 'เชื่อมต่อ (Up)',
    portDown: 'ไม่เชื่อมต่อ (Down)',
    portWarning: 'พบข้อผิดพลาดเล็กน้อย',
    portError: 'พอร์ตเสีย',
    portFaultCrc: 'CRC Error สูงผิดปกติ สายหรือหัว RJ45 น่าจะเสีย ต้องเปลี่ยนสาย',
    portFaultErrdisable: 'พอร์ตถูกตัดอัตโนมัติ (err-disabled) จาก BPDU Guard มีคนต่อสวิตช์แปลกปลอม สั่งปิด/เปิดพอร์ตใหม่เพื่อกู้คืน',
    portSfp: 'พอร์ตอัปสตรีม SFP+ 10G',
    portDetailsTitle: 'รายละเอียดพอร์ตสวิตช์',
    portInterface: 'ชื่ออินเทอร์เฟซ',
    operationalStatus: 'สถานะการทำงาน',
    negotiatedSpeed: 'ความเร็วที่เจรจาได้',
    vlanAssigned: 'VLAN ที่กำหนด',
    duplexMode: 'โหมด Duplex',
    poeDraw: 'การจ่ายไฟ PoE',
    inOutRate: 'อัตราทราฟฟิก เข้า/ออก',
    errorDiscards: 'แพ็กเก็ต Error/Discard',
    connectedMacHost: 'MAC / อุปกรณ์ที่ต่ออยู่',
    adminToggleState: 'สลับเปิด/ปิดพอร์ต (Admin State)',

    // VLANs
    vlanAnalytics: 'การตรวจสอบและวิเคราะห์ปริมาณการใช้งาน VLAN',
    addVlan: '+ เพิ่ม VLAN ใหม่',
    vlanId: 'VLAN ID',
    vlanName: 'ชื่อเครือข่าย VLAN',
    subnet: 'Subnet / CIDR',
    gateway: 'Default Gateway',
    activePortsCount: 'จำนวนพอร์ตที่ใช้งาน',
    dhcpUsage: 'การใช้งาน IP DHCP Pool',
    bandwidthUsage: 'อัตราการใช้ทราฟฟิก (Mbps)',

    // Access Points
    apClusters: 'คลัสเตอร์จุดกระจายสัญญาณไร้สาย (Wi-Fi APs)',
    apName: 'ชื่ออุปกรณ์ AP',
    ssids: 'SSID ที่กำลังกระจาย',
    channelsPower: 'แชนแนล / กำลังส่ง TX',
    avgRssi: 'ระดับสัญญาณเฉลี่ย (RSSI)',
    connectedUsers: 'ผู้ใช้งานที่เชื่อมต่อ',
    rebootAp: 'รีบูต AP',
    rebootingAp: 'กำลังส่งคำสั่งรีบูต...',
    channelOptimization: 'วิเคราะห์คลื่นและปรับจูนความถี่',

    // Clients
    activeClientSessions: 'รายการเซสชันอุปกรณ์ลูกข่าย (Read-Only)',
    clientReadonlyNotice: 'มุมมองสำหรับตรวจสอบและวิเคราะห์การใช้งานเท่านั้น (ระบบปิดการตัดการเชื่อมต่ออัตโนมัติเพื่อความปลอดภัยของระบบ)',
    hostname: 'ชื่อเครื่อง (Hostname)',
    macAddress: 'MAC Address',
    connectedNode: 'โหนดที่เชื่อมต่ออยู่',
    bandSignal: 'ย่านความถี่ / สัญญาณ (RSSI)',
    txRxRates: 'อัตรา รับ/ส่ง ข้อมูล',
    duration: 'ระยะเวลาเชื่อมต่อ',
    devicePlatform: 'ระบบปฏิบัติการ / ผู้ผลิต',

    // Topology
    interactiveTopology: 'แผนผังระบบเครือข่ายแบบโต้ตอบ (5 ระดับชั้น รองรับ 200+ โหนด)',
    editMode: 'โหมดแก้ไขแผนผัง (Edit Mode)',
    exitEditMode: 'ออกจากโหมดแก้ไข',
    saveLayout: 'บันทึกพิกัดผัง',
    layoutSaved: 'บันทึกพิกัดแผนผังลงในเครื่องเรียบร้อยแล้ว!',
    addNode: '+ เพิ่มโหนดใหม่',
    connectCable: 'เชื่อมต่อสายลิงก์',
    resetView: 'รีเซ็ตมุมมอง',
    zoomIn: 'ซูมเข้า',
    zoomOut: 'ซูมออก',
    searchNode: 'ค้นหาโหนดในผัง...',
    collapseSubtree: 'ยุบกลุ่มโหนด',
    expandSubtree: 'ขยายกลุ่มโหนด',
    hostsSubtreeCount: 'อุปกรณ์ลูกข่ายภายในกลุ่ม',
    cableType: 'ประเภทสายลิงก์',
    linkHint: 'ลากจากจุด ● ใต้อุปกรณ์ไปวางบนอุปกรณ์อื่นเพื่อเชื่อมสาย · คลิกที่สายเพื่อเปลี่ยนประเภทหรือลบ',
    linkPickTarget: 'คลิกอุปกรณ์ปลายทางเพื่อเชื่อมสาย (กด Esc เพื่อยกเลิก)',
    linkCreated: 'เชื่อมสายลิงก์เรียบร้อยแล้ว',
    linkExists: 'อุปกรณ์สองตัวนี้เชื่อมกันอยู่แล้ว',
    deleteLink: 'ลบสาย',
    viewSwitchPorts: 'ดูพอร์ตสวิตช์',

    // Alerts
    alarmIncidentDeck: 'เดสก์แจ้งเตือนเหตุการณ์และภัยคุกคามในระบบ',
    severityAll: 'ทุกระดับความรุนแรง',
    severityCritical: 'วิกฤต (Critical)',
    severityWarning: 'เตือนภัย (Warning)',
    severityInfo: 'ข้อมูล (Info)',
    alertIncident: 'เหตุการณ์ที่ตรวจพบ',
    timestamp: 'วัน-เวลาที่เกิดเหตุ',
    device: 'อุปกรณ์ต้นเหตุ',
    alertStatus: 'สถานะการจัดการ',
    acknowledgeAction: 'รับทราบเหตุ (Acknowledge)',
    acknowledgedBy: 'รับทราบโดย',
    resolveAction: 'ปิดเหตุการณ์ (Resolve)',
    ackModalTitle: 'บันทึกการรับทราบเหตุการณ์ (Incident Note)',
    ackModalPrompt: 'กรุณากรอกรายละเอียดหรือหมายเหตุการแก้ไขปัญหาเบื้องต้น:',
    ackModalPlaceholder: 'ตัวอย่าง: กำลังดำเนินการสลับสายแลนสำรอง, หรือ ส่งทีมช่างเข้าตรวจสอบตู้แร็ค...',
    ackConfirmButton: 'ยืนยันการรับทราบเหตุและบันทึกโน้ต',
    cancel: 'ยกเลิก',
    save: 'บันทึก',
    notesHistory: 'ประวัติบันทึกหมายเหตุการตรวจสอบ',

    // Syslog
    syslogTitle: 'บันทึกเหตุการณ์ระบบเครือข่าย (Syslog)',
    searchLogs: 'ค้นหาข้อความ Log, Host, IP...',
    exportLogs: 'ส่งออกข้อมูล (CSV)',
    facility: 'Facility',
    severity: 'ระดับความรุนแรง',
    hostIp: 'โฮสต์ / ไอพี',
    logMessage: 'ข้อความบันทึก',

    // Statistics
    statsTitle: 'การวิเคราะห์สถิติและการกระจายตัวของทราฟฟิก',
    trafficDistribution: 'สัดส่วนโปรโตคอลการใช้งาน',
    bandwidthTrends: 'แนวโน้มการใช้งานแบนด์วิดท์รอบ 7 วัน',
    topTalkers: 'อุปกรณ์ที่ใช้แบนด์วิดท์สูงสุด (Top Talkers)',

    // Users (Admin Only)
    userManagement: 'การจัดการผู้ใช้งานและการควบคุมสิทธิ์ (RBAC)',
    adminOnlyNote: 'เฉพาะผู้ดูแลระบบ (Admin) เท่านั้นที่สามารถจัดการผู้ใช้งานและกำหนดสิทธิ์ได้',
    createUser: '+ สร้างบัญชีผู้ใช้งานใหม่',
    userName: 'ชื่อ-นามสกุล',
    userEmail: 'อีเมลประจำตัว',
    department: 'แผนก/ฝ่าย',
    customPermissions: 'สิทธิ์การทำงานละเอียด (Permissions)',
    canEditDevices: 'แก้ไข/เพิ่ม/ลบ อุปกรณ์เครือข่าย',
    canManageUsers: 'จัดการผู้ใช้งานและสิทธิ์',
    canEditTopology: 'แก้ไขแผนผังเครือข่าย',
    canImportConfig: 'อิมพอร์ตไฟล์ Config',
    canAcknowledgeAlerts: 'รับทราบการแจ้งเตือนพร้อมใส่หมายเหตุ',
    canModifySettings: 'แก้ไขการตั้งค่าระบบและ Webhook',
    togglePassword: 'แสดง/ซ่อนรหัสผ่าน',
    statusActive: 'ใช้งานปกติ',
    statusSuspended: 'ถูกระงับสิทธิ์',

    // Settings
    settingsTitle: 'การตั้งค่าระบบ NetMonitor',
    generalSettings: 'ข้อมูลทั่วไปและการเชื่อมต่อ',
    pollingSettings: 'ความถี่การตรวจวัด SNMP Polling Interval',
    webhookSettings: 'ปลายทางส่งข้อความเตือน (Webhooks & Notifications)',
    telegramToken: 'Telegram Bot Token',
    telegramChatId: 'Telegram Chat ID',
    emailAlertsTo: 'อีเมลสำหรับรับข้อความแจ้งเตือนด่วน',
    testWebhook: 'ทดสอบส่งข้อความแจ้งเตือน',
    testWebhookSuccess: 'ส่งข้อความทดสอบสำเร็จเรียบร้อยแล้ว!',
    sessionTimeout: 'ระยะเวลาตัดเซสชันอัตโนมัติ (Session Timeout)',
    saveSettings: 'บันทึกการตั้งค่าระบบ',
    settingsSaved: 'บันทึกการตั้งค่าทั้งหมดเรียบร้อยแล้ว',

    // Auth Pages
    loginTitle: 'เข้าสู่ระบบ NetMonitor',
    loginSubtitle: 'ระบบบริหารจัดการและตรวจวัดโครงสร้างเครือข่ายระดับองค์กร',
    usernameOrEmail: 'ชื่อผู้ใช้ หรือ อีเมล',
    password: 'รหัสผ่าน',
    rememberMe: 'จดจำการเข้าสู่ระบบ',
    forgotPasswordLink: 'ลืมรหัสผ่าน?',
    loginButton: 'เข้าสู่ระบบ',
    noAccount: 'ยังไม่มีบัญชี?',
    registerHere: 'ลงทะเบียนใช้งานใหม่',
    registerTitle: 'สมัครสมาชิกบัญชีผู้ใช้ใหม่',
    registerSubtitle: 'ผู้ลงทะเบียนคนแรกสุดของระบบจะได้รับสิทธิ์ Admin โดยอัตโนมัติ',
    confirmPassword: 'ยืนยันรหัสผ่านอีกครั้ง',
    registerButton: 'สร้างบัญชีผู้ใช้งาน',
    haveAccount: 'มีบัญชีอยู่แล้ว?',
    loginHere: 'เข้าสู่ระบบที่นี่',
    firstUserNotice: '💡 สิทธิพิเศษ: หากคุณเป็นผู้ลงทะเบียนคนแรกในระบบ บัญชีนี้จะได้รับสิทธิ์ "Admin" สูงสุดทันที',
    
    // Forgot & Reset Password
    forgotTitle: 'กู้คืนรหัสผ่าน NetMonitor',
    forgotSubtitle: 'กรอกอีเมลที่ลงทะเบียนไว้ในระบบ เพื่อรับลิงก์และรหัส OTP กู้คืนรหัสผ่าน',
    sendResetLink: 'ส่งลิงก์กู้คืนรหัสผ่าน',
    resetEmailSent: 'รหัส OTP กู้คืนรหัสผ่านถูกส่งไปยังอีเมลของคุณเรียบร้อยแล้ว!',
    proceedToReset: 'ไปที่หน้าตั้งรหัสผ่านใหม่',
    resetTitle: 'ตั้งรหัสผ่านใหม่ (Reset Password)',
    resetSubtitle: 'กรอกรหัส OTP ยืนยันตัวตน พร้อมตั้งรหัสผ่านความปลอดภัยใหม่',
    otpCode: 'รหัสความปลอดภัย OTP (เช่น NET-849201)',
    newPassword: 'รหัสผ่านใหม่',
    confirmNewPassword: 'ยืนยันรหัสผ่านใหม่อีกครั้ง',
    submitNewPassword: 'บันทึกรหัสผ่านใหม่',
    resetSuccess: 'เปลี่ยนรหัสผ่านสำเร็จแล้ว! กรุณาเข้าสู่ระบบด้วยรหัสผ่านใหม่',
    backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',
    otpExpired: 'รหัส OTP หมดอายุแล้ว (มีอายุใช้งาน 15 นาที) กรุณากดขอรหัสใหม่',
    noteRequiredError: 'กรุณากรอกรายละเอียดหรือหมายเหตุการตรวจสอบก่อนยืนยัน (ห้ามเป็นค่าว่าง)',
    linkAlreadyExists: 'มีเส้นทางการเชื่อมต่อ (Link) ระหว่างคู่อุปกรณ์นี้อยู่แล้วในระบบ',
    accessDeniedTitle: '403 - ปฏิเสธการเข้าถึง (Access Denied / Forbidden)',
    accessDeniedMessage: 'คุณไม่มีสิทธิ์การใช้งานสำหรับเข้าถึงหน้านี้ สิทธิ์ปัจจุบันของคุณ:',
    returnToDashboard: 'กลับสู่หน้าแดชบอร์ดหลัก',
    firstRegistrantBadge: 'ผู้ลงทะเบียนคนแรกจะได้รับสิทธิ์ Admin สูงสุดโดยอัตโนมัติ',
    coreInfrastructure: 'โครงสร้างพื้นฐานหลัก',
    viewerClearanceTitle: 'ระดับสิทธิ์ ผู้สังเกตการณ์ (Viewer)',
    viewerClearanceDesc: 'โหมดอ่านอย่างเดียว ล็อคการแก้ไขคอนฟิกและการกดรับทราบเหตุการณ์',
    engineerAccessTitle: 'ระดับสิทธิ์ วิศวกรเครือข่าย (Engineer)',
    engineerAccessDesc: 'สามารถจัดการอุปกรณ์และ Topology ได้ เมนูจัดการสิทธิ์ผู้ใช้ล็อคสำหรับ Admin',
    rootAdminTitle: 'ระดับสิทธิ์ ผู้ดูแลระบบสูงสุด (Root Admin)',
    rootAdminDesc: 'สิทธิ์เต็มรูปแบบ: จัดการอุปกรณ์, RBAC, แผนผังโครงข่าย และตั้งค่าระบบ',

    // Quick Test Buttons
    quickTestRoles: 'ปุ่มทดสอบสลับสิทธิ์ด่วน (Mock Login Roles):',
    loginAsAdmin: 'ทดสอบเข้าเป็น Admin',
    loginAsEngineer: 'ทดสอบเข้าเป็น Engineer',
    loginAsViewer: 'ทดสอบเข้าเป็น Viewer',

    // Config Import Modal
    configImportTitle: 'สร้างอุปกรณ์จาก Config',
    configImportSub: 'อัปโหลด Config เพื่อสร้างอุปกรณ์ใหม่ ระบบจะเพิ่มลงในรายการอุปกรณ์และผัง Topology ให้อัตโนมัติ',
    cfgStepDevice: 'เลือกอุปกรณ์',
    cfgStepConfig: 'ใส่ Config',
    cfgStepApply: 'วิธีนำไปใช้',
    cfgUploadFile: 'อัปโหลดไฟล์',
    cfgTemplatePlaceholder: 'ใช้เทมเพลต...',
    cfgResetRunning: 'กลับไปใช้ Config ปัจจุบัน',
    cfgDropHint: 'ปล่อยไฟล์ที่นี่ (.cfg, .txt, .json, .conf)',
    cfgEditorHint: 'พิมพ์ วางคำสั่ง หรือลากไฟล์มาวางในช่องนี้ได้เลย',
    configEditor: 'แก้ไข',
    compareDiff: 'ดูการเปลี่ยนแปลง',
    syntaxValid: 'Config ถูกต้อง',
    syntaxWarning: 'มีข้อควรระวัง (ยังนำไปใช้ได้)',
    syntaxError: 'พบข้อผิดพลาด ต้องแก้ก่อนนำไปใช้',
    cfgLine: 'บรรทัด',
    cfgLines: 'บรรทัด',
    cfgNoChanges: 'ยังไม่มีการเปลี่ยนแปลงจาก Config ปัจจุบัน',
    modeMerge: 'รวมกับ Config เดิม',
    modeMergeDesc: 'เพิ่ม/แก้เฉพาะคำสั่งที่ใส่ ส่วนอื่นคงเดิม (แนะนำ)',
    modeReplace: 'แทนที่ทั้งหมด',
    modeReplaceDesc: 'ลบ Config เดิมทั้งหมด แล้วใช้ชุดใหม่นี้แทน',
    commitConfirmed: 'ย้อนกลับอัตโนมัติภายใน 5 นาที ถ้าอุปกรณ์ขาดการติดต่อ',
    cfgAutoBackup: 'ระบบจะสำรอง Config เดิมให้อัตโนมัติก่อนนำไปใช้',
    cfgSummary: 'การเปลี่ยนแปลง',
    applyAndDeploy: 'นำไปใช้กับอุปกรณ์',
    cfgDeploying: 'กำลังนำไปใช้...',
    deploySuccess: 'นำ Config ไปใช้สำเร็จ',
    cfgConfirmReplace: 'Config เดิมทั้งหมดของ {name} จะถูกแทนที่ ต้องการดำเนินการต่อหรือไม่?',
    cfgConfirmDiscard: 'สิ่งที่แก้ไขไว้จะหายไป ต้องการเปลี่ยนอุปกรณ์หรือไม่?',

    // Dashboard status cards
    statusOnline: 'ออนไลน์ (Online)',
    statusWarning: 'แจ้งเตือน (Warning)',
    statusOffline: 'ออฟไลน์ (Offline)',

    // Devices search & filter
    locationFilter: 'สถานที่',
    allLocations: 'ทุกสถานที่',
    trafficInOut: 'Traffic เข้า / ออก',

    // Alerts page
    alertsSubtitle: 'ติดตามเหตุการณ์ผิดปกติแบบเรียลไทม์ พร้อมบันทึกการตรวจสอบและประวัติการดำเนินการ',
    alertsSearchPlaceholder: 'ค้นหาเหตุการณ์ อุปกรณ์ IP หรือบันทึก...',
    alertStatusLabel: 'สถานะ',
    alertStatusAll: 'ทุกสถานะ',
    alertStatusActive: 'รอดำเนินการ',
    alertStatusAcknowledged: 'รับทราบแล้ว',
    alertStatusResolved: 'แก้ไขแล้ว',
    alertsEmpty: 'ไม่พบเหตุการณ์ที่ตรงกับตัวกรอง',
    alertDeviceLabel: 'อุปกรณ์',
    alertAckByLabel: 'รับทราบโดย',
    alertAuthorLabel: 'ผู้บันทึก',

    // Settings
    uiLanguageLabel: 'ภาษาที่ใช้แสดงผล',
    sshConnect: 'เปิด SSH ด้วย PuTTY',
    devicesEmpty: 'ไม่พบอุปกรณ์ที่ตรงกับตัวกรอง',
    openRuckusOne: 'เปิด RUCKUS One',
    ruckusOneUrlLabel: 'ลิงก์ RUCKUS One ของคณะ',
    ruckusOneUrlHint: 'กดเมนู "จุดกระจายสัญญาณไร้สาย" ด้านซ้ายแล้วจะเปิดลิงก์นี้ในแท็บใหม่ บัญชีภูมิภาคเอเชียใช้ https://asia.ruckus.cloud',
    sshOffline: 'อุปกรณ์ออฟไลน์ เชื่อมต่อ SSH ไม่ได้',

    // Create device from config
    cfgStepDeviceInfo: 'ข้อมูลอุปกรณ์',
    cfgStepTopology: 'ตำแหน่งในผัง Topology',
    cfgParsedHint: 'ระบบอ่านชื่อ, IP, ผู้ผลิต และเวอร์ชันจาก Config ให้อัตโนมัติ แก้ไขได้ก่อนสร้าง',
    cfgVendor: 'ผู้ผลิต',
    cfgModel: 'รุ่น',
    cfgFirmware: 'เวอร์ชันระบบปฏิบัติการ',
    cfgRack: 'ตู้แร็ค',
    cfgConnectTo: 'เชื่อมต่อกับ',
    cfgNoConnection: 'ไม่เชื่อมต่อ (วางไว้อย่างเดียว)',
    cfgLinkType: 'ชนิดสายเชื่อมต่อ',
    cfgTopologyHint: 'อุปกรณ์จะถูกวางไว้ใต้อุปกรณ์ที่เชื่อมต่อในผัง Topology ลากย้ายได้ภายหลัง',
    cfgCreateButton: 'สร้างอุปกรณ์',
    cfgCreated: 'สร้างอุปกรณ์สำเร็จ',
    cfgNeedConfig: 'ใส่ Config ก่อน',
    cfgNeedName: 'ต้องระบุชื่ออุปกรณ์',
    cfgNeedIp: 'ต้องระบุ IP Address',
    cfgBadIp: 'รูปแบบ IP Address ไม่ถูกต้อง',
    cfgNeedModel: 'ต้องระบุรุ่นอุปกรณ์',
    cfgDuplicateName: 'มีอุปกรณ์ชื่อนี้อยู่แล้ว',
    cfgDuplicateIp: 'มีอุปกรณ์ที่ใช้ IP นี้อยู่แล้ว',

    // Backup manager
    backupManagerTitle: 'สำรองข้อมูล Config',
    backupManagerSub: 'สำรอง Config ของอุปกรณ์อัตโนมัติ ดู เปรียบเทียบ ดาวน์โหลด และกู้คืนได้',
    runGlobalBackup: 'สำรองทุกอุปกรณ์ตอนนี้',
    globalBackupSuccess: 'สำรอง Config ทุกอุปกรณ์เรียบร้อยแล้ว',
    globalBackupRunning: 'กำลังสำรอง Config ทุกอุปกรณ์...',
    restoreSuccess: 'กู้คืน Config ลงอุปกรณ์เรียบร้อยแล้ว',
    totalBackups: 'จำนวนไฟล์สำรองทั้งหมด',
    protectedDevices: 'อุปกรณ์ที่มีไฟล์สำรอง',
    lastBackupTime: 'สำรองล่าสุด',
    storageUsage: 'พื้นที่ที่ใช้',
    backupArchiveTitle: 'คลังไฟล์สำรอง',
    versionTag: 'ชื่อเวอร์ชัน',
    backupTimestamp: 'เวลาที่สำรอง',
    fileSize: 'ขนาดไฟล์',
    checksum: 'Checksum',
    triggeredBy: 'ผู้สั่งสำรอง',
    viewConfig: 'ดู Config',
    downloadConfig: 'ดาวน์โหลด .cfg',
    restoreConfig: 'กู้คืนลงอุปกรณ์',
    deleteBackup: 'ลบไฟล์สำรอง',
    confirmRestore: 'ยืนยันการกู้คืน Config',
    deleteBackupConfirm: 'ลบไฟล์สำรองนี้ถาวร ไม่สามารถกู้กลับได้',

    // In-app notifications
    appNotifTitle: 'แจ้งเตือนใหม่',
    enableDesktopNotif: 'เปิดการแจ้งเตือนบนเดสก์ท็อป',
    // ---- Collector / SNMP (backend integration) ----
    snmpVersion: 'เวอร์ชัน SNMP',
    snmpPort: 'พอร์ต SNMP (UDP)',
    snmpCommunity: 'Community สำหรับอ่าน (Read-only)',
    snmpCommunityHint: 'ใช้ดึงค่า CPU/RAM/พอร์ต อ่านอย่างเดียว',
    snmpWriteCommunity: 'Community สำหรับเขียน (Read-write)',
    snmpWriteCommunityHint: 'ต้องมีถ้าจะสั่งปิด/เปิดพอร์ตจากหน้าเว็บ ถ้าเว้นว่าง = อ่านอย่างเดียว',
    snmpOptional: 'ไม่ใส่ก็ได้',
    snmpV3User: 'ชื่อผู้ใช้ SNMPv3',
    snmpV3Level: 'ระดับความปลอดภัย',
    snmpV3AuthPrivHint: 'ยืนยันตัวตน + เข้ารหัส',
    snmpV3AuthProtocol: 'อัลกอริทึมยืนยันตัวตน',
    snmpV3AuthKey: 'รหัสยืนยันตัวตน (Auth key)',
    snmpV3PrivProtocol: 'อัลกอริทึมเข้ารหัส',
    snmpV3PrivKey: 'รหัสเข้ารหัส (Priv key)',
    snmpTestButton: 'ทดสอบเชื่อมต่อ SNMP',
    snmpTesting: 'กำลังทดสอบ...',
    snmpTestOk: 'เชื่อมต่อสำเร็จ อุปกรณ์ตอบกลับแล้ว',
    snmpTestFailed: 'เชื่อมต่อไม่สำเร็จ',
    snmpFoundVlans: 'พบ VLAN',
    snmpMissingMetrics: 'อุปกรณ์ไม่ตอบค่าเหล่านี้ (จะแสดงเป็น 0)',
    cfgStepSnmp: 'ตั้งค่าการเชื่อมต่อ SNMP แล้วกดทดสอบ',
    cfgSnmpHint: 'ค่าเหล่านี้คือสิ่งที่ระบบใช้ดึงข้อมูลจริงจากอุปกรณ์ ควรกดทดสอบก่อนบันทึก',
    cfgNeedConfigOrSnmp: 'ต้องทดสอบ SNMP ให้ผ่าน หรือใส่ไฟล์ Config อย่างน้อยหนึ่งอย่าง',
    cfgNeedV3User: 'SNMPv3 ต้องระบุชื่อผู้ใช้',
    cfgCreating: 'กำลังสร้าง...',
    cfgCreateFailed: 'สร้างอุปกรณ์ไม่สำเร็จ',

    // ---- Statuses and labels shared across pages ----
    cpu: 'CPU',
    ram: 'หน่วยความจำ',
    ports: 'พอร์ต',
    yourRole: 'สิทธิ์ของบัญชีนี้',
    manageRoles: 'จัดการสิทธิ์ผู้ใช้',
    restoringSession: 'กำลังตรวจสอบการเข้าสู่ระบบ...',
    signingIn: 'กำลังเข้าสู่ระบบ...',
    passwordTooShort: 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
    firstRunHint: 'บัญชีผู้ดูแลระบบบัญชีแรกสร้างจากคำสั่ง npm run db:seed ที่เครื่องเซิร์ฟเวอร์ หรือกดสมัครสมาชิก (ผู้สมัครคนแรกจะได้สิทธิ์ Admin)',
    registerPolicyTitle: 'นโยบายการให้สิทธิ์',
    registerPolicyDetail: 'เซิร์ฟเวอร์จะให้สิทธิ์ Admin กับผู้สมัครคนแรก (หรือเมื่อไม่มี Admin ที่ใช้งานอยู่) ที่เหลือจะได้สิทธิ์ Engineer',
    registerSuccessPrefix: 'สร้างบัญชีสำเร็จ ได้รับสิทธิ์',
    registerSuccessSuffix: 'กำลังเข้าสู่ระบบ...',
    ackFailed: 'บันทึกการรับทราบไม่สำเร็จ',

    // ---- Backup Manager ----
    restoreStaged: 'นำ Config ย้อนกลับในระบบแล้ว ต้องนำไปใช้ที่ตัวอุปกรณ์เองอีกครั้ง',
    restoreFailed: 'ย้อนกลับ Config ไม่สำเร็จ',
    backupDeleted: 'ลบไฟล์สำรองแล้ว',
    backupDeleteFailed: 'ลบไฟล์สำรองไม่สำเร็จ',
    backupDeleteAdminOnly: 'เฉพาะผู้ดูแลระบบ (Admin) เท่านั้นที่ลบไฟล์สำรองย้อนหลังได้',
    globalBackupFailed: 'สำรอง Config ทั้งระบบไม่สำเร็จ',
    // ---- Dashboard / Statistics (real telemetry) ----
    telemetrySubtitle: 'ปริมาณทราฟฟิกรวมทุกพอร์ตที่ระบบเก็บได้จากตัวนับของอุปกรณ์',
    inbound: 'ขาเข้า',
    outbound: 'ขาออก',
    peak: 'สูงสุด',
    traffic: 'ทราฟฟิก',
    total: 'รวม',
    rank: 'อันดับ',
    vlan: 'VLAN',
    portName: 'พอร์ต',
    connectedMac: 'MAC ที่ตรวจพบ',
    snmpProbeStatus: 'อุปกรณ์ที่ตอบ SNMP',
    devicesOverThreshold: 'อุปกรณ์ที่ใช้ทรัพยากรเกินเกณฑ์',
    activeCriticalAlarms: 'แจ้งเตือนระดับวิกฤตที่ยังไม่แก้',
    collectorUnreachable: 'ติดต่อเซิร์ฟเวอร์เก็บข้อมูล (Collector) ไม่ได้',
    noDevicesYet: 'ยังไม่มีอุปกรณ์ในระบบ',
    noDevicesYetHint: 'ไปที่หน้า Backup แล้วกด "นำเข้า Config / เพิ่มอุปกรณ์" ใส่ IP กับค่า SNMP แล้วกดทดสอบ',
    noTelemetryYet: 'ยังไม่มีข้อมูลที่เก็บไว้ ระบบจะวาดกราฟหลังดึงข้อมูลรอบแรกเสร็จ',
    loadingTelemetry: 'กำลังโหลดข้อมูลย้อนหลัง...',
    statsSubtitle: 'แนวโน้มปริมาณทราฟฟิกและการใช้ทรัพยากร คำนวณจากตัวนับ SNMP ที่เก็บไว้',
    last6h: '6 ชม.',
    last24h: '24 ชม.',
    last7d: '7 วัน',
    peakInbound: 'ขาเข้าสูงสุด',
    peakOutbound: 'ขาออกสูงสุด',
    peakCpuLabel: 'CPU สูงสุด',
    samplesStored: 'จำนวนข้อมูลที่เก็บ',
    throughputTrend: 'แนวโน้มปริมาณทราฟฟิก',
    throughputTrendHint: 'รวมทุกอุปกรณ์ หน่วย Mbps',
    trafficByVlan: 'ทราฟฟิกแยกตาม VLAN',
    trafficByVlanHint: 'รวมจากพอร์ตที่อยู่ใน VLAN นั้น',
    noVlanTraffic: 'ยังไม่มีทราฟฟิกใน VLAN ใด ๆ',
    noProtocolBreakdown: 'SNMP บอกได้แค่ปริมาณข้อมูล ไม่บอกว่าเป็นโปรโตคอลอะไร ถ้าต้องการต้องเพิ่ม NetFlow/IPFIX หรือ DPI',
    topPortsHint: 'เรียงตามทราฟฟิกล่าสุดของแต่ละพอร์ต',
    noPortTraffic: 'ยังไม่มีพอร์ตที่มีทราฟฟิก (ต้องดึงข้อมูลอย่างน้อย 2 รอบจึงคำนวณอัตราได้)',
    // ---- Settings: collector status and honest labels ----
    settingsSubtitle: 'รอบการดึงข้อมูล SNMP, สำรอง Config, การแจ้งเตือนภายนอก และข้อกำหนดด้านความปลอดภัย',
    collectorStatus: 'สถานะเซิร์ฟเวอร์เก็บข้อมูล (Collector)',
    collectorPolling: 'รอบการดึงข้อมูล',
    pollingDisabled: 'ปิดการดึงข้อมูลอยู่',
    every: 'ทุก',
    monitoredDevices: 'อุปกรณ์ที่เฝ้าระวัง',
    thresholdsLabel: 'เกณฑ์แจ้งเตือน',
    lastPollCycle: 'ดึงข้อมูลรอบล่าสุด',
    reachable: 'ติดต่อได้',
    failed: 'ล้มเหลว',
    pollFailures: 'อุปกรณ์ที่ดึงข้อมูลไม่สำเร็จในรอบล่าสุด',
    pollingIntervalLabel: 'รอบการดึงข้อมูล SNMP',
    pollingIntervalHint: 'ค่าเริ่มต้น 300 วินาที เพื่อลดภาระเครือข่าย (เซิร์ฟเวอร์ไม่รับค่าต่ำกว่า 15 วินาที)',
    snmpTimeoutLabel: 'เวลารอคำตอบ SNMP (ms)',
    snmpTimeoutHint: 'ถ้าอุปกรณ์ไม่ตอบในเวลานี้ จะถือว่าออฟไลน์',
    packetLossLabel: 'เกณฑ์ Packet Loss (%)',
    noEffectYet: 'ค่านี้ยังไม่มีผล: ระบบดึงข้อมูลผ่าน SNMP เท่านั้น จึงยังไม่วัด Packet Loss',
    thresholdsEnvHint: 'เกณฑ์ CPU/RAM ที่ใช้แจ้งเตือนตั้งที่ไฟล์ server/.env (CPU_ALERT_THRESHOLD, RAM_ALERT_THRESHOLD)',
    settingsSaveFailed: 'บันทึกการตั้งค่าไม่สำเร็จ',
    saving: 'กำลังบันทึก...',
    minutes: 'นาที',
    webhooksNotActive: 'ยังไม่ส่งแจ้งเตือนจริง: ค่าที่กรอกจะถูกเก็บไว้ แต่ระบบยังไม่ส่ง Telegram หรืออีเมล',
    securityTab: 'ความปลอดภัยและเซสชัน',
    securitySessionsTitle: 'ความปลอดภัยและการจัดการเซสชันการเข้าสู่ระบบ',
    sessionTimeoutHint: 'เวลาหมดอายุจริงกำหนดด้วย JWT_EXPIRES_IN ในไฟล์ server/.env ค่านี้ยังเก็บไว้อย่างเดียว',
    // ---- Devices page: SNMP editing and polling control ----
    editDeviceTitle: 'แก้ไขอุปกรณ์ (สถานที่ / แร็ค / SNMP)',
    snmpKeepBlankHint: 'ช่องรหัสจะว่างไว้เสมอเพื่อความปลอดภัย ถ้าไม่กรอกจะใช้ค่าเดิมที่เก็บไว้ ถ้ากรอกจะเปลี่ยนเป็นค่าใหม่',
    lastPollError: 'ข้อผิดพลาดจากการดึงข้อมูลครั้งล่าสุด',
    deviceSaveFailed: 'บันทึกข้อมูลอุปกรณ์ไม่สำเร็จ',
    pollNow: 'ดึงข้อมูลเดี๋ยวนี้',
    pollFailed: 'ดึงข้อมูลไม่สำเร็จ',
    pausePolling: 'หยุดดึงข้อมูลอุปกรณ์นี้',
    resumePolling: 'กลับมาดึงข้อมูลอุปกรณ์นี้',
    paused: 'หยุดชั่วคราว',
    pollingPausedHint: 'หยุดดึงข้อมูลอุปกรณ์นี้อยู่ ค่าที่แสดงเป็นค่าล่าสุดก่อนหยุด',
    quickSnapshot: 'สำรอง Config ทันที',
    snapshotArchivedFor: 'สำรอง Config แล้วสำหรับ',
    backupFailed: 'สำรอง Config ไม่สำเร็จ',
    // ---- Ports / VLANs / APs: real actions and their failure messages ----
    disablePort: 'ปิดพอร์ต (shutdown)',
    enablePort: 'เปิดพอร์ต (no shutdown)',
    applyingPortChange: 'กำลังสั่งอุปกรณ์...',
    portChangeFailed: 'อุปกรณ์ไม่ยอมรับคำสั่งเปลี่ยนสถานะพอร์ต',
    portOfflineHint: 'ติดต่ออุปกรณ์ไม่ได้ จึงยังสั่งเปลี่ยนสถานะพอร์ตไม่ได้จนกว่าจะกลับมาออนไลน์',
    portReadOnlyHint: 'โหมดดูอย่างเดียว: การสั่งปิด/เปิดพอร์ตต้องมีสิทธิ์ Engineer หรือ Admin',
    vlanIdRange: 'VLAN ID ต้องอยู่ระหว่าง 1 ถึง 4094',
    vlanExists: 'VLAN นี้มีอยู่แล้ว',
    vlanCreateFailed: 'บันทึก VLAN ไม่สำเร็จ',
    apRebootUnavailable: 'การรีบูต AP ต้องทำผ่าน RUCKUS One ซึ่งยังไม่ได้เชื่อมต่อ',
    // SNMP round-trip time, shown where an ICMP latency used to be
    snmpRtt: 'เวลาตอบ SNMP',
    offlineReason: 'ไม่ตอบ SNMP',
    // ---- Telegram notifications ----
    telegramEnabled: 'เปิดการแจ้งเตือน',
    telegramNotifyRecovery: 'แจ้งตอนกลับมาปกติ',
    telegramMinSeverity: 'ส่งตั้งแต่ระดับ',
    severityInfoUp: 'ทุกระดับ (Info ขึ้นไป)',
    severityWarningUp: 'Warning ขึ้นไป',
    severityCriticalOnly: 'เฉพาะ Critical',
    telegramCooldown: 'เว้นระยะส่งซ้ำ (นาที)',
    telegramCooldownHint: 'เรื่องเดิมของอุปกรณ์เดิมจะไม่ส่งซ้ำภายในเวลานี้ กัน Alert ถล่มตอนอุปกรณ์ขึ้น ๆ ลง ๆ',
    telegramTokenStored: 'เก็บไว้แล้ว — กรอกใหม่เพื่อเปลี่ยน',
    telegramTokenHint: 'เซิร์ฟเวอร์ไม่ส่ง token กลับมาให้เบราว์เซอร์ ปล่อยว่างไว้ = ใช้ค่าเดิม',
    telegramTesting: 'กำลังส่ง...',
    telegramTestOk: 'ส่งสำเร็จ ไปดูในแชท Telegram ได้เลย',
    telegramTestFailed: 'ส่งไม่สำเร็จ',
    emailNotActive: 'อีเมลยังไม่ทำงาน: ค่าถูกเก็บไว้ แต่ยังไม่มีการเชื่อมต่อ SMTP',
    // ---- Email notifications over SMTP ----
    emailSectionTitle: 'แจ้งเตือนทางอีเมล (SMTP)',
    emailEnabled: 'เปิดการแจ้งเตือนทางอีเมล',
    emailMinSeverity: 'ส่งอีเมลตั้งแต่ระดับ',
    emailTestButton: 'ทดสอบส่งอีเมล',
    emailTesting: 'กำลังส่ง...',
    emailTestOk: 'ส่งอีเมลสำเร็จ ไปดูในกล่องจดหมายได้เลย',
    emailTestFailed: 'ส่งอีเมลไม่สำเร็จ',
    smtpUser: 'บัญชีอีเมลที่ใช้ส่ง',
    smtpPassword: 'รหัสผ่านสำหรับแอป (App Password)',
    smtpPasswordHint: 'ของ Gmail เป็นรหัส 16 ตัว ไม่ใช่รหัสผ่านบัญชีปกติ เซิร์ฟเวอร์ไม่ส่งค่านี้กลับมาที่เบราว์เซอร์ ปล่อยว่าง = ใช้ค่าเดิม',
    smtpHost: 'เซิร์ฟเวอร์ SMTP',
    smtpPort: 'พอร์ต',
    smtpPortHint: '587 = STARTTLS, 465 = SSL',
    gmailAppPasswordHint: 'ถ้าใช้ Gmail ต้องเปิดการยืนยันตัวตนสองขั้นก่อน แล้วสร้าง App Password ที่หน้า myaccount.google.com/apppasswords นำรหัส 16 ตัวมากรอกในช่องด้านบน (มีช่องว่างคั่นก็ได้ ระบบตัดให้เอง)',
  },
  en: {
    // App Brand & Topbar
    appName: 'NetMonitor',
    appSub: 'Enterprise Network Device and Wireless Access Point Monitoring and Management System',
    coreGateway: 'Core Gateway',
    gatewayOnline: 'Online',
    pingLatency: 'Latency',
    searchPlaceholder: 'Search Devices, IPs, MACs, VLANs or SSIDs...',
    profile: 'Profile',
    role: 'Role',
    logout: 'Logout',
    switchRole: 'Quick Role Switcher',
    notifications: 'System Notifications',
    noAlerts: 'No pending critical alerts',
    viewAllAlerts: 'View all incident alerts',

    // Roles
    roleAdmin: 'Administrator (Admin)',
    roleEngineer: 'Network Engineer',
    roleViewer: 'Viewer (Read-Only)',

    // Navigation Menu
    navDashboard: 'Dashboard Overview',
    navDevices: 'Hardware Inventory',
    navPorts: 'Switch Port Matrix',
    navVlans: 'VLAN Traffic Analytics',
    navAPs: 'Wireless AP Clusters',
    navClients: 'Active Client Sessions',
    navTopology: 'Interactive Topology',
    navAlerts: 'Incident Alarm Deck',
    navEventLogs: 'Syslog Event Logs',
    navStatistics: 'Traffic Analytics',
    navUsers: 'User Management & RBAC',
    navSettings: 'System Settings',

    // Dashboard
    totalHardware: 'Total Hardware Nodes',
    activeNodes: 'Healthy Active Nodes',
    disconnectedNodes: 'Disconnected / Warnings',
    broadcastingAPs: 'Broadcasting APs',
    activeClients: 'Connected Clients',
    totalThroughput: 'Total Aggregate Throughput',
    telemetryTitle: 'Real-Time Network Telemetry (Mbps)',
    cpuMemoryTitle: 'Systemwide CPU & RAM Utilization',
    topVlansTitle: 'Top VLAN Traffic Consumption',
    topologyPreview: 'Network Topology Preview',
    viewFullTopology: 'Open Fullscreen Topology Canvas',
    criticalIncidents: 'Active Critical Incidents',
    systemHealth: 'System Health Index',
    nominalStatus: 'Operation Nominal & Resilient',
    lastSyncTime: 'Last telemetry sync at',
    refreshData: 'Refresh Telemetry',

    // Devices
    devicesInventory: 'Network Hardware Inventory',
    addDevice: '+ Add New Device',
    deviceTypeFilter: 'Device Category',
    statusFilter: 'Status',
    allTypes: 'All Categories',
    allStatuses: 'All Statuses',
    deviceName: 'Device Name',
    ipAddress: 'IP Address',
    type: 'Category',
    modelVendor: 'Vendor / Model',
    locationRack: 'Location / Rack',
    uptime: 'Uptime',
    cpuRam: 'CPU / RAM Usage',
    portsUp: 'Ports Up / Total',
    actions: 'Actions',
    inspectPorts: 'Inspect Ports',
    importConfig: 'Import Config',
    editDevice: 'Edit',
    deleteDevice: 'Delete',
    readOnlyNotice: 'Read-only mode: Modifications are restricted to Admin/Engineer.',

    // Ports
    switchPortMatrix: 'Physical Switch Port Status Matrix',
    selectSwitch: 'Select Switch Hardware:',
    portStatusLegend: 'Port Status Legend:',
    portUp: 'Active (Link Up)',
    portDown: 'Disconnected (Down)',
    portWarning: 'Degraded (minor errors)',
    portError: 'Faulty port',
    portFaultCrc: 'Excessive CRC errors: the cable or RJ45 connector is likely faulty and should be replaced',
    portFaultErrdisable: 'Port err-disabled by BPDU Guard (an unauthorized switch was connected); shut / no shut to recover',
    portSfp: '10G SFP+ Uplink Trunk',
    portDetailsTitle: 'Port Interface Diagnostics',
    portInterface: 'Interface Name',
    operationalStatus: 'Operational State',
    negotiatedSpeed: 'Negotiated Speed',
    vlanAssigned: 'Assigned VLAN',
    duplexMode: 'Duplex Mode',
    poeDraw: 'PoE Power Consumption',
    inOutRate: 'In / Out Traffic Rate',
    errorDiscards: 'Error & Discard Packets',
    connectedMacHost: 'Connected Device / MAC',
    adminToggleState: 'Toggle Administrative Port State',

    // VLANs
    vlanAnalytics: 'VLAN Segmentation & Bandwidth Analytics',
    addVlan: '+ Add New VLAN',
    vlanId: 'VLAN ID',
    vlanName: 'VLAN Network Name',
    subnet: 'Subnet / CIDR',
    gateway: 'Default Gateway',
    activePortsCount: 'Active Assigned Ports',
    dhcpUsage: 'DHCP Pool Saturation',
    bandwidthUsage: 'Traffic Rate (Mbps)',

    // Access Points
    apClusters: 'Enterprise Wireless Access Point Clusters',
    apName: 'AP Hostname',
    ssids: 'Broadcast SSIDs',
    channelsPower: 'Channels / TX Power',
    avgRssi: 'Average RSSI Signal',
    connectedUsers: 'Associated Clients',
    rebootAp: 'Reboot AP',
    rebootingAp: 'Dispatching reboot command...',
    channelOptimization: 'Auto RF Frequency Optimization',

    // Clients
    activeClientSessions: 'Active Client Sessions (Read-Only Inspection)',
    clientReadonlyNotice: 'Read-Only telemetry inspection view (Disconnection controls disabled to maintain critical infrastructure stability).',
    hostname: 'Hostname',
    macAddress: 'MAC Address',
    connectedNode: 'Associated Node',
    bandSignal: 'Radio Band / RSSI',
    txRxRates: 'Data Rates (Tx / Rx)',
    duration: 'Session Duration',
    devicePlatform: 'OS Platform / Vendor',

    // Topology
    interactiveTopology: 'Visual Network Topology Map (5-Tier Architecture with 200+ Nodes Support)',
    editMode: 'Topology Edit Mode',
    exitEditMode: 'Exit Edit Mode',
    saveLayout: 'Save Node Coordinates',
    layoutSaved: 'Topology coordinates successfully saved to local persistent storage!',
    addNode: '+ Add Node',
    connectCable: 'Connect Cable Link',
    resetView: 'Reset Canvas View',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    searchNode: 'Find node on canvas...',
    collapseSubtree: 'Collapse Group',
    expandSubtree: 'Expand Group',
    hostsSubtreeCount: 'Host Nodes Inside Group',
    cableType: 'Link Medium',
    linkHint: 'Drag from the ● handle under a node onto another node to connect · Click a cable to change its type or delete it',
    linkPickTarget: 'Click the destination node to connect (press Esc to cancel)',
    linkCreated: 'Cable link connected',
    linkExists: 'These two nodes are already linked',
    deleteLink: 'Delete link',
    viewSwitchPorts: 'View Switch Ports',

    // Alerts
    alarmIncidentDeck: 'System Alarm & Incident Monitoring Deck',
    severityAll: 'All Severities',
    severityCritical: 'Critical Alarm',
    severityWarning: 'Warning Alert',
    severityInfo: 'Informational',
    alertIncident: 'Detected Incident',
    timestamp: 'Occurrence Timestamp',
    device: 'Originating Device',
    alertStatus: 'Resolution State',
    acknowledgeAction: 'Acknowledge',
    acknowledgedBy: 'Acknowledged by',
    resolveAction: 'Mark Resolved',
    ackModalTitle: 'Incident Acknowledgment & Note Filing',
    ackModalPrompt: 'Provide diagnostic notes or remediation action taken:',
    ackModalPlaceholder: 'E.g., Initiated failover to secondary trunk line, dispatched field tech to inspect optic transceiver...',
    ackConfirmButton: 'Confirm Acknowledgment & Record Note',
    cancel: 'Cancel',
    save: 'Save',
    notesHistory: 'Investigation Notes & Audit Trail',

    // Syslog
    syslogTitle: 'Syslog Event & Audit Trail Stream',
    searchLogs: 'Filter Syslog message, host, IP...',
    exportLogs: 'Export Syslog (CSV)',
    facility: 'Facility',
    severity: 'Severity Level',
    hostIp: 'Source Host / IP',
    logMessage: 'Message Payload',

    // Statistics
    statsTitle: 'Longitudinal Traffic Analytics & Statistics',
    trafficDistribution: 'Protocol Bandwidth Breakdown',
    bandwidthTrends: '7-Day Cumulative Bandwidth Profile',
    topTalkers: 'Top Bandwidth Consuming Hosts',

    // Users (Admin Only)
    userManagement: 'User Management & Role-Based Access Control (RBAC)',
    adminOnlyNote: 'Restricted area: Only Administrators have clearance to modify user access and role privileges.',
    createUser: '+ Create Authorised User',
    userName: 'Full Name',
    userEmail: 'Corporate Email',
    department: 'Department',
    customPermissions: 'Granular Permissions Override',
    canEditDevices: 'Add / Edit / Delete Hardware Devices',
    canManageUsers: 'Grant User Access & Permissions',
    canEditTopology: 'Modify Topology Canvas Layout',
    canImportConfig: 'Import Running / Startup Configs',
    canAcknowledgeAlerts: 'Acknowledge Alarms with Diagnostic Notes',
    canModifySettings: 'Configure Webhooks & System Parameters',
    togglePassword: 'Show / Hide Password',
    statusActive: 'Active Access',
    statusSuspended: 'Suspended',

    // Settings
    settingsTitle: 'NetMonitor Infrastructure Configuration',
    generalSettings: 'General System & Gateway Coordinates',
    pollingSettings: 'SNMP & Telemetry Polling Intervals',
    webhookSettings: 'Integration Webhooks & Notification Channels',
    telegramToken: 'Telegram Bot Token',
    telegramChatId: 'Telegram Chat ID',
    emailAlertsTo: 'Urgent Dispatch Alert Email',
    testWebhook: 'Transmit Test Dispatch',
    testWebhookSuccess: 'Test dispatch successfully fired to configured webhook endpoint!',
    sessionTimeout: 'Inactivity Session Timeout',
    saveSettings: 'Commit Configuration Changes',
    settingsSaved: 'All parameters committed successfully',

    // Auth Pages
    loginTitle: 'NetMonitor Console Access',
    loginSubtitle: 'Enterprise Network Device and Wireless Access Point Monitoring Console',
    usernameOrEmail: 'Username or Email Address',
    password: 'Password',
    rememberMe: 'Keep me authenticated',
    forgotPasswordLink: 'Forgot credentials?',
    loginButton: 'Sign In to Console',
    noAccount: "Don't have an account?",
    registerHere: 'Register New Account',
    registerTitle: 'Create Console Operator Account',
    registerSubtitle: 'The initial registered user is granted Administrator (Admin) privileges automatically.',
    confirmPassword: 'Confirm Password',
    registerButton: 'Register Operator Account',
    haveAccount: 'Already registered?',
    loginHere: 'Sign In here',
    firstUserNotice: '💡 First Registrant Policy: If no users currently exist in the database, this account will automatically receive root Admin credentials.',
    
    // Forgot & Reset Password
    forgotTitle: 'Recover NetMonitor Account',
    forgotSubtitle: 'Enter your registered email address to receive an authentication OTP code and recovery instructions.',
    sendResetLink: 'Transmit Recovery OTP',
    resetEmailSent: 'Recovery OTP code has been dispatched to your email address!',
    proceedToReset: 'Proceed to Reset Password',
    resetTitle: 'Establish New Password',
    resetSubtitle: 'Input the dispatched OTP verification code and set your updated secure credentials.',
    otpCode: 'OTP Security Code (e.g., NET-849201)',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    submitNewPassword: 'Commit New Password',
    resetSuccess: 'Password has been reset successfully! You can now sign in with your new credentials.',
    backToLogin: 'Return to Sign In',
    otpExpired: 'OTP code has expired (15-minute validity ceiling). Please request a new code.',
    noteRequiredError: 'Diagnostic investigation note is mandatory (Cannot be empty or whitespace only).',
    linkAlreadyExists: 'A network link between these two nodes already exists.',
    accessDeniedTitle: '403 - Access Forbidden (Clearance Required)',
    accessDeniedMessage: 'Your operator role lacks sufficient clearance to access this module. Current clearance:',
    returnToDashboard: 'Return to Dashboard Console',
    firstRegistrantBadge: 'The initial registered user automatically receives Administrator clearance.',
    coreInfrastructure: 'Core Infrastructure',
    viewerClearanceTitle: 'Viewer Clearance',
    viewerClearanceDesc: 'Read-only mode. Configuration edits & acknowledge actions are locked.',
    engineerAccessTitle: 'Engineer Access',
    engineerAccessDesc: 'Technical ops enabled. User accounts panel is managed by Admin.',
    rootAdminTitle: 'Root Admin Clearance',
    rootAdminDesc: 'Full authority: Devices, RBAC, Topology & System Settings.',

    // Quick Test Buttons
    quickTestRoles: 'Mock RBAC Role Switcher:',
    loginAsAdmin: 'Test as Admin',
    loginAsEngineer: 'Test as Engineer',
    loginAsViewer: 'Test as Viewer',

    // Config Import Modal
    configImportTitle: 'Create Device from Config',
    configImportSub: 'Upload a config to create a new device; it is added to the inventory and the topology map',
    cfgStepDevice: 'Choose device',
    cfgStepConfig: 'Provide config',
    cfgStepApply: 'How to apply',
    cfgUploadFile: 'Upload file',
    cfgTemplatePlaceholder: 'Use a template...',
    cfgResetRunning: 'Reset to current config',
    cfgDropHint: 'Drop file here (.cfg, .txt, .json, .conf)',
    cfgEditorHint: 'Type, paste commands, or drag a file onto this box',
    configEditor: 'Edit',
    compareDiff: 'Review changes',
    syntaxValid: 'Config looks good',
    syntaxWarning: 'Warnings found (you can still deploy)',
    syntaxError: 'Errors found - fix them before deploying',
    cfgLine: 'Line',
    cfgLines: 'lines',
    cfgNoChanges: 'No changes from the current config yet',
    modeMerge: 'Merge with current config',
    modeMergeDesc: 'Adds or updates only these commands; everything else stays (recommended)',
    modeReplace: 'Replace entire config',
    modeReplaceDesc: 'Removes the current config and uses this one instead',
    commitConfirmed: 'Auto-rollback within 5 minutes if the device becomes unreachable',
    cfgAutoBackup: 'The current config is backed up automatically before deploying',
    cfgSummary: 'Changes',
    applyAndDeploy: 'Deploy to device',
    cfgDeploying: 'Deploying...',
    deploySuccess: 'Config deployed successfully',
    cfgConfirmReplace: 'The entire current config of {name} will be replaced. Continue?',
    cfgConfirmDiscard: 'Your edits will be lost. Switch device?',

    // Dashboard status cards
    statusOnline: 'Online',
    statusWarning: 'Warning',
    statusOffline: 'Offline',

    // Devices search & filter
    locationFilter: 'Location',
    allLocations: 'All locations',
    trafficInOut: 'Traffic In / Out',

    // Alerts page
    alertsSubtitle: 'Real-time incident response deck with role-based diagnostic note filing & historical audit trail',
    alertsSearchPlaceholder: 'Search incident, device, IP or note...',
    alertStatusLabel: 'Status',
    alertStatusAll: 'All States',
    alertStatusActive: 'Active Incidents',
    alertStatusAcknowledged: 'Acknowledged',
    alertStatusResolved: 'Resolved',
    alertsEmpty: 'No incident alarms found matching selected filters.',
    alertDeviceLabel: 'Device',
    alertAckByLabel: 'Ack by',
    alertAuthorLabel: 'Author',

    // Settings
    uiLanguageLabel: 'Display Language',
    sshConnect: 'Open SSH in PuTTY',
    devicesEmpty: 'No devices match the current filters',
    openRuckusOne: 'Open RUCKUS One',
    ruckusOneUrlLabel: 'Faculty RUCKUS One URL',
    ruckusOneUrlHint: 'Opened in a new tab from the Wi-Fi access points menu on the left; APAC accounts use https://asia.ruckus.cloud',
    sshOffline: 'Device is offline; SSH unavailable',

    // Create device from config
    cfgStepDeviceInfo: 'Device details',
    cfgStepTopology: 'Place on the topology map',
    cfgParsedHint: 'Name, IP, vendor and OS version are read from the config; edit them before creating',
    cfgVendor: 'Vendor',
    cfgModel: 'Model',
    cfgFirmware: 'OS version',
    cfgRack: 'Rack',
    cfgConnectTo: 'Connect to',
    cfgNoConnection: 'No connection (place only)',
    cfgLinkType: 'Link type',
    cfgTopologyHint: 'The device is placed below the node it connects to; you can drag it later',
    cfgCreateButton: 'Create device',
    cfgCreated: 'Device created',
    cfgNeedConfig: 'Add a config first',
    cfgNeedName: 'Device name is required',
    cfgNeedIp: 'IP address is required',
    cfgBadIp: 'IP address is not valid',
    cfgNeedModel: 'Device model is required',
    cfgDuplicateName: 'A device with this name already exists',
    cfgDuplicateIp: 'A device already uses this IP',

    // Backup manager
    backupManagerTitle: 'Config Backup Manager',
    backupManagerSub: 'Automatic device config backups you can view, compare, download and restore',
    runGlobalBackup: 'Back up all devices now',
    globalBackupSuccess: 'All device configs backed up',
    globalBackupRunning: 'Backing up all device configs...',
    restoreSuccess: 'Config restored to the device',
    totalBackups: 'Total backups',
    protectedDevices: 'Devices with backups',
    lastBackupTime: 'Last backup',
    storageUsage: 'Storage used',
    backupArchiveTitle: 'Backup Archive',
    versionTag: 'Version',
    backupTimestamp: 'Backed up at',
    fileSize: 'Size',
    checksum: 'Checksum',
    triggeredBy: 'Triggered by',
    viewConfig: 'View config',
    downloadConfig: 'Download .cfg',
    restoreConfig: 'Restore to device',
    deleteBackup: 'Delete backup',
    confirmRestore: 'Confirm config restore',
    deleteBackupConfirm: 'This backup will be deleted permanently and cannot be recovered',

    // In-app notifications
    appNotifTitle: 'New alert',
    enableDesktopNotif: 'Enable desktop notifications',
    // ---- Collector / SNMP (backend integration) ----
    snmpVersion: 'SNMP version',
    snmpPort: 'SNMP port (UDP)',
    snmpCommunity: 'Read-only community',
    snmpCommunityHint: 'Used to read CPU, memory and interface counters',
    snmpWriteCommunity: 'Read-write community',
    snmpWriteCommunityHint: 'Required to shut or enable a port from NetMonitor. Leave empty for read-only.',
    snmpOptional: 'optional',
    snmpV3User: 'SNMPv3 username',
    snmpV3Level: 'Security level',
    snmpV3AuthPrivHint: 'authenticated and encrypted',
    snmpV3AuthProtocol: 'Authentication algorithm',
    snmpV3AuthKey: 'Authentication key',
    snmpV3PrivProtocol: 'Privacy algorithm',
    snmpV3PrivKey: 'Privacy key',
    snmpTestButton: 'Test SNMP connection',
    snmpTesting: 'Testing...',
    snmpTestFailed: 'Could not reach the device',
    snmpTestOk: 'Connected, the device answered',
    snmpFoundVlans: 'VLANs found',
    snmpMissingMetrics: 'The agent did not answer these (they will read 0)',
    cfgStepSnmp: 'Set up the SNMP connection and test it',
    cfgSnmpHint: 'These are the parameters the collector polls with. Test them before saving.',
    cfgNeedConfigOrSnmp: 'Either pass the SNMP test or provide a config file',
    cfgNeedV3User: 'SNMPv3 requires a username',
    cfgCreating: 'Registering...',
    cfgCreateFailed: 'Could not register the device',

    // ---- Statuses and labels shared across pages ----
    cpu: 'CPU',
    ram: 'Memory',
    ports: 'Ports',
    yourRole: 'Your role',
    manageRoles: 'Manage user roles',
    restoringSession: 'Checking your session...',
    signingIn: 'Signing in...',
    passwordTooShort: 'Password must be at least 8 characters',
    firstRunHint: 'The first administrator account comes from `npm run db:seed` on the server, or from Register (the first registrant becomes Admin).',
    registerPolicyTitle: 'Role assignment policy',
    registerPolicyDetail: 'The server grants Admin to the first account, or to the first one registered while no active Admin exists. Everyone else gets Engineer.',
    registerSuccessPrefix: 'Account created with',
    registerSuccessSuffix: 'privileges. Redirecting...',
    ackFailed: 'Could not save the acknowledgement',

    // ---- Backup Manager ----
    restoreStaged: 'The archived config is now the recorded config. Apply it on the device to take effect.',
    restoreFailed: 'Could not roll back the configuration',
    backupDeleted: 'Backup archive deleted',
    backupDeleteFailed: 'Could not delete the backup',
    backupDeleteAdminOnly: 'Only Administrator accounts can purge historic backup archives.',
    globalBackupFailed: 'The global backup run failed',
    // ---- Dashboard / Statistics (real telemetry) ----
    telemetrySubtitle: 'Total traffic across every polled interface, from the devices own counters',
    inbound: 'Inbound',
    outbound: 'Outbound',
    peak: 'peak',
    traffic: 'Traffic',
    total: 'Total',
    rank: 'Rank',
    vlan: 'VLAN',
    portName: 'Port',
    connectedMac: 'Learned MAC',
    snmpProbeStatus: 'Devices answering SNMP',
    devicesOverThreshold: 'Devices over threshold',
    activeCriticalAlarms: 'Open critical alarms',
    collectorUnreachable: 'Cannot reach the NetMonitor collector',
    noDevicesYet: 'No devices are being monitored yet',
    noDevicesYetHint: 'Open the Backup page and use "Import config / Add device": enter the IP and SNMP settings, then test them.',
    noTelemetryYet: 'Nothing stored yet. The chart appears after the first poll cycle completes.',
    loadingTelemetry: 'Loading stored telemetry...',
    statsSubtitle: 'Throughput and resource trends, computed from the stored SNMP counters',
    last6h: '6h',
    last24h: '24h',
    last7d: '7d',
    peakInbound: 'Peak inbound',
    peakOutbound: 'Peak outbound',
    peakCpuLabel: 'Peak CPU',
    samplesStored: 'Samples stored',
    throughputTrend: 'Throughput trend',
    throughputTrendHint: 'All devices combined, in Mbps',
    trafficByVlan: 'Traffic by VLAN',
    trafficByVlanHint: 'Summed from the ports in each VLAN',
    noVlanTraffic: 'No VLAN is carrying traffic yet',
    noProtocolBreakdown: 'SNMP counters report how much traffic crossed an interface, not which protocols it was. A protocol breakdown needs NetFlow/IPFIX or DPI.',
    topPortsHint: 'Ranked by each port latest measured rate',
    noPortTraffic: 'No port is carrying traffic yet. Rates need at least two poll cycles.',
    // ---- Settings: collector status and honest labels ----
    settingsSubtitle: 'SNMP polling cadence, config backups, external notifications and security constraints',
    collectorStatus: 'Collector status',
    collectorPolling: 'Polling',
    pollingDisabled: 'Polling disabled',
    every: 'every',
    monitoredDevices: 'Monitored devices',
    thresholdsLabel: 'Alert thresholds',
    lastPollCycle: 'Last poll cycle',
    reachable: 'reachable',
    failed: 'failed',
    pollFailures: 'Devices the last cycle could not reach',
    pollingIntervalLabel: 'SNMP polling interval',
    pollingIntervalHint: 'Defaults to 300 s to keep traffic off the production network. The server rejects anything under 15 s.',
    snmpTimeoutLabel: 'SNMP request timeout (ms)',
    snmpTimeoutHint: 'A device that does not answer within this window counts as offline',
    packetLossLabel: 'Packet loss ceiling (%)',
    noEffectYet: 'No effect yet: an SNMP-only collector has no packet-loss measurement.',
    thresholdsEnvHint: 'The CPU and RAM alert thresholds are set in server/.env (CPU_ALERT_THRESHOLD, RAM_ALERT_THRESHOLD).',
    settingsSaveFailed: 'Could not save the settings',
    saving: 'Saving...',
    minutes: 'minutes',
    webhooksNotActive: 'Not active yet: these values are stored, but nothing sends Telegram messages or email.',
    securityTab: 'Security & sessions',
    securitySessionsTitle: 'Security and authentication session governance',
    sessionTimeoutHint: 'The real session lifetime is JWT_EXPIRES_IN in server/.env. This value is stored only.',
    // ---- Devices page: SNMP editing and polling control ----
    editDeviceTitle: 'Edit device (location / rack / SNMP)',
    snmpKeepBlankHint: 'Key fields are always shown blank. Leave them empty to keep the stored secret, or type a value to replace it.',
    lastPollError: 'Last poll error',
    deviceSaveFailed: 'Could not save the device',
    pollNow: 'Poll now',
    pollFailed: 'The poll failed',
    pausePolling: 'Pause polling for this device',
    resumePolling: 'Resume polling for this device',
    paused: 'Paused',
    pollingPausedHint: 'Polling is paused for this device. The values shown are the last ones measured.',
    quickSnapshot: 'Archive config snapshot now',
    snapshotArchivedFor: 'Snapshot archived for',
    backupFailed: 'Could not archive the config',
    // ---- Ports / VLANs / APs: real actions and their failure messages ----
    disablePort: 'Disable port (shutdown)',
    enablePort: 'Enable port (no shutdown)',
    applyingPortChange: 'Asking the device...',
    portChangeFailed: 'The device refused the port state change',
    portOfflineHint: 'unreachable, so port changes cannot be applied until it answers again',
    portReadOnlyHint: 'Read-only view: changing a port administratively requires Engineer or Admin clearance.',
    vlanIdRange: 'VLAN ID must be between 1 and 4094',
    vlanExists: 'This VLAN already exists',
    vlanCreateFailed: 'Could not save the VLAN',
    apRebootUnavailable: 'Rebooting an access point goes through RUCKUS One, which is not connected yet',
    // SNMP round-trip time, shown where an ICMP latency used to be
    snmpRtt: 'SNMP response',
    offlineReason: 'No SNMP reply',
    // ---- Telegram notifications ----
    telegramEnabled: 'Send notifications',
    telegramNotifyRecovery: 'Notify on recovery',
    telegramMinSeverity: 'Send from level',
    severityInfoUp: 'Every level (Info and up)',
    severityWarningUp: 'Warning and up',
    severityCriticalOnly: 'Critical only',
    telegramCooldown: 'Repeat cooldown (minutes)',
    telegramCooldownHint: 'The same topic on the same device will not send again within this window, so a flapping link cannot flood the chat.',
    telegramTokenStored: 'stored — type a new one to replace it',
    telegramTokenHint: 'The server never sends the token back to the browser. Leave it empty to keep the stored one.',
    telegramTesting: 'Sending...',
    telegramTestOk: 'Sent. Check your Telegram chat.',
    telegramTestFailed: 'Could not send',
    emailNotActive: 'Email is not wired up yet: the address is stored, but there is no SMTP transport.',
    // ---- Email notifications over SMTP ----
    emailSectionTitle: 'Email notifications (SMTP)',
    emailEnabled: 'Send email notifications',
    emailMinSeverity: 'Email from level',
    emailTestButton: 'Send test email',
    emailTesting: 'Sending...',
    emailTestOk: 'Sent. Check the inbox.',
    emailTestFailed: 'Could not send the email',
    smtpUser: 'Sending account',
    smtpPassword: 'App Password',
    smtpPasswordHint: 'For Gmail this is the 16-character App Password, not the normal account password. The server never sends it back to the browser; leave it empty to keep the stored one.',
    smtpHost: 'SMTP server',
    smtpPort: 'Port',
    smtpPortHint: '587 = STARTTLS, 465 = SSL',
    gmailAppPasswordHint: 'For Gmail, turn on 2-step verification first, then create an App Password at myaccount.google.com/apppasswords and paste the 16 characters above. Spaces are fine, they are stripped automatically.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = localStorage.getItem('netmonitor_lang');
    return (saved === 'en' || saved === 'th') ? saved : 'th';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('netmonitor_lang', newLang);
  };

  const t = (key: string): string => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
