import React, { useState, useEffect, useRef, useMemo } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { useNetworkData } from '../../context/NetworkDataContext';
import { useAuth } from '../../context/AuthContext';
import { DeviceType, SnmpProbeResult, TopologyLink } from '../../types';
import { api } from '../../services/api';
import {
  EMPTY_SNMP_FORM,
  SnmpFields,
  SnmpTestPanel,
  toSnmpPayload,
  type SnmpFormValues,
} from './snmp-fields';
import {
  FileCode2,
  Upload,
  X,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  FileText,
  Server,
  GitFork,
  Radio,
} from 'lucide-react';

interface ConfigImportModalProps {
  isOpen: boolean;
  onClose: () => void;
}


// Built-in Enterprise Templates
const SAMPLE_TEMPLATES = {
  cisco_trunk: {
    name: 'Cisco IOS-XE: Enterprise 802.1Q Trunk & Voice VLAN',
    deviceType: 'Switch',
    content: `! Cisco IOS-XE Software Enterprise Switch Template
! Auto-Generated by NetMonitor Configuration Manager
hostname SW-Enterprise-Access
!
vlan 10
 name MGMT-CORP
vlan 20
 name DATA-USERS
vlan 30
 name VOICE-IP
vlan 50
 name WIFI-CORP
!
interface TenGigabitEthernet1/0/1
 description Primary Core Uplink [802.1Q Trunk]
 switchport mode trunk
 switchport trunk allowed vlan 10,20,30,50,70,100
 switchport nonegotiate
 spanning-tree guard root
!
interface range GigabitEthernet1/0/1 - 24
 description User Access Workstation & VoIP Phone
 switchport mode access
 switchport access vlan 20
 switchport voice vlan 30
 spanning-tree portfast
 spanning-tree bpduguard enable
!
end`,
  },
  cisco_ospf: {
    name: 'Cisco IOS-XE: OSPF Routing & WAN Sub-interfaces',
    deviceType: 'Router',
    content: `! Cisco IOS-XE Software WAN Router Template
hostname WAN-Edge-Gateway
!
ip routing
ip domain-lookup
!
interface GigabitEthernet0/0/0
 description Primary ISP Upstream Fiber
 ip address 203.158.0.2 255.255.255.252
 no shutdown
!
interface GigabitEthernet0/0/1
 description LAN Core Transit
 ip address 192.168.100.1 255.255.255.248
 ip ospf 1 area 0
 ip ospf network point-to-point
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 NetMonSecretKey99
 no shutdown
!
router ospf 1
 router-id 192.168.100.1
 passive-interface GigabitEthernet0/0/0
 log-adjacency-changes detail
!
line vty 0 4
 transport input ssh
 logging synchronous
!
end`,
  },
  forti_firewall: {
    name: 'Fortinet FortiOS: NGFW Security Policy & NAT Overload',
    deviceType: 'Firewall',
    content: `# FortiOS Version 7.4.2 Configuration Template
config system global
    set hostname "Perimeter-NGFW-Cluster"
    set timezone 55
end
config system interface
    edit "port1"
        set alias "WAN-Internet"
        set mode static
        set ip 192.168.100.2 255.255.255.248
        set allowaccess ping ssh https
    next
    edit "port2"
        set alias "LAN-Internal"
        set mode static
        set ip 10.10.0.254 255.255.255.0
        set allowaccess ping
    next
end
config firewall policy
    edit 101
        set name "Corp-Users-To-Internet"
        set srcintf "port2"
        set dstintf "port1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set utm-status enable
        set ssl-ssh-profile "certificate-inspection"
        set ips-sensor "default"
        set nat enable
    next
end`,
  },
  json_interface: {
    name: 'JSON Format: Interface & Policy Specification',
    deviceType: 'All',
    content: `{
  "schema": "netmonitor.config.v2",
  "device": {
    "hostname": "Core-L3-SW-01",
    "managementIp": "10.10.0.1",
    "snmpCommunity": "public_ro"
  },
  "vlans": [
    { "id": 10, "name": "MGMT", "subnet": "10.10.10.0/24", "gateway": "10.10.10.1" },
    { "id": 20, "name": "CORP-LAN", "subnet": "10.10.20.0/24", "gateway": "10.10.20.1" },
    { "id": 30, "name": "VOIP", "subnet": "10.10.30.0/24", "gateway": "10.10.30.1" },
    { "id": 50, "name": "WIFI-CORP", "subnet": "10.10.50.0/24", "gateway": "10.10.50.1" }
  ],
  "monitoring": {
    "pollingIntervalSeconds": 30,
    "flowExport": "NetFlow-v9",
    "collectorIp": "10.10.100.250"
  }
}`,
  },
};

type ValidationMessage = { type: 'error' | 'warning' | 'info'; text: string; line?: number };
type ValidationResult = { status: 'idle' | 'valid' | 'warning' | 'error'; messages: ValidationMessage[] };

// Syntax & security checks for CLI (Cisco / Fortinet / Aruba) and JSON configs
const validateConfig = (content: string): ValidationResult => {
  const messages: ValidationMessage[] = [];
  let hasError = false;
  let hasWarning = false;

  if (!content.trim()) {
    return { status: 'idle', messages: [] };
  }

  if (content.trim().startsWith('{')) {
    try {
      JSON.parse(content);
      messages.push({ type: 'info', text: 'Valid JSON syntax confirmed. Complies with NetMonitor schema v2.' });
    } catch (err: any) {
      hasError = true;
      messages.push({ type: 'error', text: `JSON Parse Syntax Error: ${err.message}` });
    }
  } else {
    let foundHostname = false;
    let openBlocks = 0;

    content.split('\n').forEach((rawLine, idx) => {
      const line = rawLine.trim();
      const lower = line.toLowerCase();
      const lineNum = idx + 1;

      if (lower.startsWith('hostname ') || lower.startsWith('set hostname')) {
        foundHostname = true;
      }

      if (lower.includes('transport input telnet') || lower.includes('telnet enable')) {
        hasWarning = true;
        messages.push({ type: 'warning', line: lineNum, text: 'Insecure plaintext Telnet protocol detected. Prefer SSHv2.' });
      }

      if (lower.startsWith('password ') && !lower.includes('7 ') && !lower.includes('secret ')) {
        hasWarning = true;
        messages.push({ type: 'warning', line: lineNum, text: 'Plaintext password without encryption hash. Use "enable secret" or "service password-encryption".' });
      }

      if (lower.startsWith('ip http server') && !lower.includes('secure')) {
        hasWarning = true;
        messages.push({ type: 'warning', line: lineNum, text: 'Unencrypted HTTP management enabled. Prefer "ip http secure-server".' });
      }

      const ipMatch = line.match(/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/g);
      ipMatch?.forEach(ip => {
        if (ip.split('.').map(Number).some(o => o < 0 || o > 255)) {
          hasError = true;
          messages.push({ type: 'error', line: lineNum, text: `Invalid IP address ${ip} (each octet must be 0-255).` });
        }
      });

      // Block balance for FortiOS
      if (line.startsWith('config ') || line.startsWith('edit ')) openBlocks++;
      if (line === 'end' || line === 'next') openBlocks = Math.max(0, openBlocks - 1);
    });

    if (!foundHostname) {
      hasWarning = true;
      messages.push({ type: 'warning', text: 'No "hostname" directive. Device will keep its current name.' });
    }

    if (openBlocks > 0) {
      hasWarning = true;
      messages.push({ type: 'warning', text: `${openBlocks} unclosed configuration block(s) (missing 'end' or 'next').` });
    }
  }

  return { status: hasError ? 'error' : hasWarning ? 'warning' : 'valid', messages };
};


const DEVICE_TYPES: DeviceType[] = ['Router', 'Firewall', 'Core Switch', 'Distribution Switch', 'Edge Switch', 'Server'];

const PORTS_BY_TYPE: Record<DeviceType, number> = {
  Router: 8,
  Firewall: 18,
  'Core Switch': 48,
  'Distribution Switch': 48,
  'Edge Switch': 48,
  Server: 8,
};

// The topology node type a new device of each type usually hangs off
const PARENT_NODE_TYPE: Record<DeviceType, string> = {
  Router: 'wan',
  Firewall: 'router',
  'Core Switch': 'firewall',
  'Distribution Switch': 'core_switch',
  'Edge Switch': 'dist_switch',
  Server: 'core_switch',
};

const IPV4 = /^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/;

type DeviceForm = {
  name: string;
  ip: string;
  type: DeviceType;
  vendor: string;
  model: string;
  location: string;
  rack: string;
  firmware: string;
};

const EMPTY_FORM: DeviceForm = {
  name: '',
  ip: '',
  type: 'Edge Switch',
  vendor: '',
  model: '',
  location: '',
  rack: '',
  firmware: '',
};

// Read what the config itself states about the device: hostname, management IP, vendor, OS version, role
const parseConfig = (content: string): Partial<DeviceForm> => {
  const text = content.trim();
  if (!text) return {};

  if (text.startsWith('{')) {
    try {
      const dev = JSON.parse(text).device ?? {};
      return {
        name: dev.hostname,
        ip: dev.managementIp,
        type: DEVICE_TYPES.includes(dev.type) ? dev.type : undefined,
        vendor: dev.vendor,
        model: dev.model,
      };
    } catch {
      return {};
    }
  }

  const first = (re: RegExp) => text.match(re)?.[1];

  if (/^config system (global|interface)/m.test(text)) {
    return {
      name: first(/set hostname\s+"?([^"\s]+)"?/),
      ip: first(/set ip\s+(\d{1,3}(?:\.\d{1,3}){3})/),
      type: 'Firewall',
      vendor: 'Fortinet',
      firmware: first(/FortiOS Version\s+([\d.]+)/i) ? `FortiOS ${first(/FortiOS Version\s+([\d.]+)/i)}` : undefined,
    };
  }

  const hasSwitchports = /^\s*switchport/m.test(text);
  const routes = /^router (ospf|bgp|eigrp|rip)/m.test(text) || /^ip route /m.test(text);
  const type: DeviceType = hasSwitchports
    ? /^ip routing/m.test(text) || routes
      ? 'Distribution Switch'
      : 'Edge Switch'
    : routes
    ? 'Router'
    : 'Edge Switch';
  const vendor = /aruba|aos-cx/i.test(text) ? 'Aruba Networks' : /cisco|ios-xe|\bios\b/i.test(text) ? 'Cisco Systems' : undefined;
  const version = first(/^version\s+(\S+)/m);

  return {
    name: first(/^hostname\s+"?([^"\s]+)"?/m),
    ip: first(/ip address\s+(\d{1,3}(?:\.\d{1,3}){3})/),
    type,
    vendor,
    firmware: version ? `${vendor === 'Aruba Networks' ? 'AOS-CX' : 'Cisco IOS-XE'} ${version}` : undefined,
  };
};


const StepLabel: React.FC<{ step: number; children: React.ReactNode }> = ({ step, children }) => (
  <div className="flex items-center gap-2 text-xs font-bold text-slate-800 dark:text-slate-200">
    <span className="w-5 h-5 rounded-full bg-cyan-600 text-white text-[11px] flex items-center justify-center">{step}</span>
    {children}
  </div>
);

const inputClass =
  'w-full bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg p-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-cyan-500';

// Import a config file to create a new device: it is added to the inventory and placed on the topology map
export const ConfigImportModal: React.FC<ConfigImportModalProps> = ({ isOpen, onClose }) => {
  const { t } = useLanguage();
  const { devices, topologyNodes, provisionDeviceFromConfig } = useNetworkData();
  const { isViewer } = useAuth();

  const [configContent, setConfigContent] = useState('');
  const [fileName, setFileName] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [form, setForm] = useState<DeviceForm>(EMPTY_FORM);
  // Fields the user typed in are not overwritten when the config is parsed again
  const [touched, setTouched] = useState<Set<keyof DeviceForm>>(new Set());
  const [parentNodeId, setParentNodeId] = useState<string>('');
  const [parentTouched, setParentTouched] = useState(false);
  const [linkType, setLinkType] = useState<TopologyLink['linkType']>('fiber_10g');
  const [createdName, setCreatedName] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [createError, setCreateError] = useState<string | null>(null);

  // SNMP credentials the collector will poll with, and the result of testing them
  const [snmp, setSnmp] = useState<SnmpFormValues>(EMPTY_SNMP_FORM);
  const [probe, setProbe] = useState<SnmpProbeResult | null>(null);
  const [isTesting, setIsTesting] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const gutterRef = useRef<HTMLDivElement>(null);

  // Start from a clean slate every time the modal opens
  useEffect(() => {
    if (!isOpen) return;
    setConfigContent('');
    setFileName('');
    setForm(EMPTY_FORM);
    setTouched(new Set());
    setParentNodeId('');
    setParentTouched(false);
    setLinkType('fiber_10g');
    setCreatedName(null);
    setCreateError(null);
    setSnmp(EMPTY_SNMP_FORM);
    setProbe(null);
  }, [isOpen]);

  // Fill the device fields from the config, leaving anything the user edited alone
  useEffect(() => {
    const parsed = parseConfig(configContent);
    setForm(prev => {
      const next = { ...prev };
      (Object.keys(parsed) as (keyof DeviceForm)[]).forEach(key => {
        const value = parsed[key];
        if (value && !touched.has(key)) (next[key] as string) = value;
      });
      return next;
    });
  }, [configContent]);

  // Suggest where the device connects on the map from its type, until the user picks one
  useEffect(() => {
    if (parentTouched) return;
    const parent = topologyNodes.find(n => n.type === PARENT_NODE_TYPE[form.type]);
    setParentNodeId(parent?.id ?? '');
    setLinkType(form.type === 'Edge Switch' || form.type === 'Server' ? 'copper_1g' : 'fiber_10g');
  }, [form.type, parentTouched, topologyNodes]);

  const validation = useMemo(() => validateConfig(configContent), [configContent]);

  // A result only describes the address and credentials it was taken with
  useEffect(() => {
    setProbe(null);
  }, [form.ip, snmp.snmpVersion, snmp.snmpPort, snmp.snmpCommunity, snmp.snmpV3User, snmp.snmpV3AuthKey, snmp.snmpV3PrivKey]);

  if (!isOpen) return null;

  const setField = (key: keyof DeviceForm, value: string) => {
    setForm(prev => ({ ...prev, [key]: value }));
    setTouched(prev => new Set(prev).add(key));
  };

  const loadContent = (content: string, name: string) => {
    setConfigContent(content);
    setFileName(name);
  };

  const processFile = (file?: File) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => {
      const text = ev.target?.result as string;
      if (text) loadContent(text, `${file.name} (${(file.size / 1024).toFixed(1)} KB)`);
    };
    reader.readAsText(file);
  };

  const handleLoadTemplate = (key: string) => {
    const tpl = SAMPLE_TEMPLATES[key as keyof typeof SAMPLE_TEMPLATES];
    if (tpl) loadContent(tpl.content, tpl.name);
  };

  const name = form.name.trim();
  const ip = form.ip.trim();
  const snmpVerified = probe?.reachable === true;
  const problems = [
    // Either the device answered SNMP, or a config file describes it. One of the two.
    !configContent.trim() && !snmpVerified && t('cfgNeedConfigOrSnmp'),
    configContent.trim() && validation.status === 'error' && t('syntaxError'),
    !name && t('cfgNeedName'),
    !ip ? t('cfgNeedIp') : !IPV4.test(ip) && t('cfgBadIp'),
    snmp.snmpVersion === '3' && !snmp.snmpV3User.trim() && t('cfgNeedV3User'),
    name && devices.some(d => d.name.toLowerCase() === name.toLowerCase()) && t('cfgDuplicateName'),
    ip && devices.some(d => d.ip === ip) && t('cfgDuplicateIp'),
  ].filter(Boolean) as string[];
  const canCreate = !isViewer && problems.length === 0;

  /**
   * Ask the device who it is, with the credentials entered above.
   *
   * On success the inventory fields are pre-filled from what the device reported, so
   * vendor, model and firmware are whatever the hardware actually says they are.
   */
  const handleTestSnmp = async () => {
    const address = form.ip.trim();
    if (!IPV4.test(address)) return;
    setIsTesting(true);
    setProbe(null);
    try {
      const result = await api.devices.testSnmp({ ip: address, ...toSnmpPayload(snmp) });
      setProbe(result);
      if (result.reachable) {
        // Only fill blanks and untouched fields; never overwrite what the operator typed
        setForm(prev => {
          const next = { ...prev };
          const fill = (key: keyof DeviceForm, value?: string) => {
            if (value && !touched.has(key) && !prev[key]) (next[key] as string) = value;
          };
          fill('name', result.suggested.name);
          fill('vendor', result.suggested.vendor);
          fill('model', result.suggested.model);
          fill('firmware', result.suggested.firmware);
          fill('location', result.suggested.location);
          return next;
        });
      }
    } catch (error) {
      setProbe({
        reachable: false,
        error: error instanceof Error ? error.message : 'SNMP test failed',
        responseMs: 0,
      });
    } finally {
      setIsTesting(false);
    }
  };

  const handleCreate = async () => {
    if (!canCreate || isCreating) return;
    setIsCreating(true);
    setCreateError(null);

    // No fabricated metrics: status starts offline and the first poll fills in
    // CPU, RAM, uptime, port counts and traffic from the device itself.
    const res = await provisionDeviceFromConfig(
      {
        name,
        ip,
        type: form.type,
        vendor: form.vendor.trim() || undefined,
        model: form.model.trim() || undefined,
        location: form.location.trim() || undefined,
        rack: form.rack.trim() || undefined,
        firmware: form.firmware.trim() || undefined,
        config: configContent.trim() || undefined,
        ...toSnmpPayload(snmp),
      },
      { parentNodeId: parentNodeId || null, linkType }
    );

    setIsCreating(false);
    if (!res.success) {
      setCreateError(res.error ?? t('cfgCreateFailed'));
      return;
    }
    setCreatedName(name);
    setTimeout(onClose, 1500);
  };

  const totalLines = configContent ? configContent.split('\n').length : 0;

  const field = (key: keyof DeviceForm, label: string, opts: { required?: boolean; mono?: boolean; placeholder?: string } = {}) => (
    <div>
      <label className="block text-[11px] text-slate-600 dark:text-slate-400 mb-1 font-medium">
        {label}
        {opts.required && <span className="text-rose-500"> *</span>}
      </label>
      <input
        type="text"
        value={form[key]}
        onChange={e => setField(key, e.target.value)}
        placeholder={opts.placeholder}
        className={`${inputClass} ${opts.mono ? 'font-mono' : ''}`}
      />
    </div>
  );

  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-md z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl max-w-3xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="px-6 py-4 flex items-center justify-between border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/30 flex items-center justify-center text-cyan-500">
              <FileCode2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900 dark:text-white">{t('configImportTitle')}</h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">{t('configImportSub')}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Success Banner */}
        {createdName && (
          <div className="p-4 bg-emerald-50 dark:bg-emerald-950/90 border-b border-emerald-300 dark:border-emerald-700 text-emerald-800 dark:text-emerald-200 text-xs flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-emerald-500" />
            <span className="font-semibold">
              {t('cfgCreated')}: {createdName}
            </span>
          </div>
        )}

        <div className="p-5 overflow-y-auto space-y-5 flex-1">
          {/* Step 1: Config */}
          <section className="space-y-2">
            <StepLabel step={1}>{t('cfgStepConfig')}</StepLabel>

            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="px-3 py-1.5 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-semibold flex items-center gap-1.5"
              >
                <Upload className="w-3.5 h-3.5" />
                {t('cfgUploadFile')}
              </button>
              <input
                ref={fileInputRef}
                type="file"
                accept=".cfg,.txt,.json,.conf,.text"
                onChange={e => {
                  processFile(e.target.files?.[0]);
                  e.target.value = '';
                }}
                className="hidden"
              />

              <select
                value=""
                onChange={e => handleLoadTemplate(e.target.value)}
                className="px-2.5 py-1.5 rounded-lg bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-xs text-slate-700 dark:text-slate-300 focus:outline-none focus:ring-2 focus:ring-cyan-500"
              >
                <option value="" disabled>
                  {t('cfgTemplatePlaceholder')}
                </option>
                {Object.entries(SAMPLE_TEMPLATES).map(([key, tpl]) => (
                  <option key={key} value={key}>
                    {tpl.name}
                  </option>
                ))}
              </select>

              {fileName && (
                <span className="text-[11px] text-cyan-600 dark:text-cyan-400 flex items-center gap-1 truncate max-w-full">
                  <FileText className="w-3.5 h-3.5 shrink-0" />
                  <span className="truncate">{fileName}</span>
                </span>
              )}
              <span className="ml-auto text-[11px] text-slate-400 font-mono">
                {totalLines} {t('cfgLines')}
              </span>
            </div>

            <div
              className="relative flex h-56 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden bg-slate-50 dark:bg-slate-950"
              onDragOver={e => {
                e.preventDefault();
                setIsDragging(true);
              }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={e => {
                e.preventDefault();
                setIsDragging(false);
                processFile(e.dataTransfer.files?.[0]);
              }}
            >
              {/* Line numbers (scroll-synced with the textarea) */}
              <div
                ref={gutterRef}
                className="w-10 py-3 overflow-hidden bg-slate-100/70 dark:bg-slate-900/60 text-slate-400 dark:text-slate-600 font-mono text-xs select-none text-right pr-2 border-r border-slate-200 dark:border-slate-800"
              >
                {Array.from({ length: Math.max(1, totalLines) }).map((_, i) => (
                  <div key={i} className="leading-5">
                    {i + 1}
                  </div>
                ))}
              </div>
              <textarea
                value={configContent}
                onChange={e => setConfigContent(e.target.value)}
                onScroll={e => {
                  if (gutterRef.current) gutterRef.current.scrollTop = e.currentTarget.scrollTop;
                }}
                spellCheck={false}
                placeholder={t('cfgEditorHint')}
                className="flex-1 bg-transparent text-slate-800 dark:text-emerald-400 font-mono text-xs p-3 focus:outline-none leading-5 resize-none whitespace-pre overflow-auto"
              />
              {isDragging && (
                <div className="absolute inset-0 border-2 border-dashed border-cyan-500 bg-cyan-500/10 rounded-xl flex flex-col items-center justify-center gap-1.5 text-cyan-700 dark:text-cyan-300 text-xs font-semibold pointer-events-none">
                  <Upload className="w-5 h-5" />
                  {t('cfgDropHint')}
                </div>
              )}
            </div>

            {/* Live validation feedback */}
            {validation.status !== 'idle' && (
              <div
                className={`p-3 rounded-xl border text-xs space-y-1.5 ${
                  validation.status === 'valid'
                    ? 'bg-emerald-50 dark:bg-emerald-950/40 border-emerald-300 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300'
                    : validation.status === 'warning'
                    ? 'bg-amber-50 dark:bg-amber-950/40 border-amber-300 dark:border-amber-800 text-amber-800 dark:text-amber-300'
                    : 'bg-rose-50 dark:bg-rose-950/40 border-rose-300 dark:border-rose-800 text-rose-800 dark:text-rose-300'
                }`}
              >
                <div className="flex items-center gap-2 font-semibold">
                  {validation.status === 'valid' ? (
                    <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  ) : validation.status === 'warning' ? (
                    <AlertTriangle className="w-4 h-4 text-amber-500" />
                  ) : (
                    <XCircle className="w-4 h-4 text-rose-500" />
                  )}
                  <span>
                    {validation.status === 'valid'
                      ? t('syntaxValid')
                      : validation.status === 'warning'
                      ? t('syntaxWarning')
                      : t('syntaxError')}
                  </span>
                </div>
                {validation.status !== 'valid' && (
                  <ul className="list-disc list-inside space-y-0.5 text-[11px] pl-1">
                    {validation.messages
                      .filter(m => m.type !== 'info')
                      .map((m, idx) => (
                        <li key={idx}>
                          {m.line && <span className="font-semibold mr-1">{t('cfgLine')} {m.line}:</span>}
                          {m.text}
                        </li>
                      ))}
                  </ul>
                )}
              </div>
            )}
          </section>

          {/* Step 2: how the collector reaches this device, and proof that it can */}
          <section className="space-y-2.5">
            <StepLabel step={2}>{t('cfgStepSnmp')}</StepLabel>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
              <Radio className="w-3.5 h-3.5 text-cyan-500" />
              {t('cfgSnmpHint')}
            </p>
            <div>
              <label className="block text-[11px] text-slate-600 dark:text-slate-400 mb-1 font-medium">
                {t('ipAddress')}
                <span className="text-rose-500"> *</span>
              </label>
              <input
                type="text"
                value={form.ip}
                onChange={e => setField('ip', e.target.value)}
                placeholder="10.10.0.5"
                className={`${inputClass} font-mono`}
              />
            </div>
            <SnmpFields value={snmp} onChange={setSnmp} />
            <SnmpTestPanel
              isTesting={isTesting}
              result={probe}
              onTest={handleTestSnmp}
              canTest={IPV4.test(form.ip.trim())}
            />
          </section>

          {/* Step 3: inventory details, pre-filled from the device or the config */}
          <section className="space-y-2">
            <StepLabel step={3}>{t('cfgStepDeviceInfo')}</StepLabel>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
              <Server className="w-3.5 h-3.5 text-cyan-500" />
              {t('cfgParsedHint')}
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {field('name', t('deviceName'), { required: true, placeholder: 'e.g. Dist-SW-Building-E' })}
              <div>
                <label className="block text-[11px] text-slate-600 dark:text-slate-400 mb-1 font-medium">
                  {t('type')}
                  <span className="text-rose-500"> *</span>
                </label>
                <select value={form.type} onChange={e => setField('type', e.target.value)} className={inputClass}>
                  {DEVICE_TYPES.map(type => (
                    <option key={type} value={type}>
                      {type}
                    </option>
                  ))}
                </select>
              </div>
              {field('vendor', t('cfgVendor'), { placeholder: 'Cisco Systems' })}
              {field('model', t('cfgModel'), { placeholder: 'Catalyst 9300-48P' })}
              {field('firmware', t('cfgFirmware'), { mono: true, placeholder: 'Cisco IOS-XE 17.09' })}
              {field('location', t('locationRack'), { placeholder: 'Building E - IDF 1' })}
              {field('rack', t('cfgRack'), { mono: true, placeholder: 'Rack-E1 (Unit 10)' })}
            </div>
          </section>

          {/* Step 4: Topology placement */}
          <section className="space-y-2">
            <StepLabel step={4}>{t('cfgStepTopology')}</StepLabel>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] text-slate-600 dark:text-slate-400 mb-1 font-medium">{t('cfgConnectTo')}</label>
                <select
                  value={parentNodeId}
                  onChange={e => {
                    setParentNodeId(e.target.value);
                    setParentTouched(true);
                  }}
                  className={inputClass}
                >
                  <option value="">{t('cfgNoConnection')}</option>
                  {topologyNodes.map(n => (
                    <option key={n.id} value={n.id}>
                      {n.label} ({n.ip})
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-[11px] text-slate-600 dark:text-slate-400 mb-1 font-medium">{t('cfgLinkType')}</label>
                <select
                  value={linkType}
                  disabled={!parentNodeId}
                  onChange={e => {
                    setLinkType(e.target.value as TopologyLink['linkType']);
                    setParentTouched(true);
                  }}
                  className={`${inputClass} disabled:opacity-50`}
                >
                  <option value="fiber_40g">40G Fiber</option>
                  <option value="fiber_10g">10G Fiber</option>
                  <option value="copper_1g">1G Copper</option>
                  <option value="trunk">802.1Q Trunk</option>
                </select>
              </div>
            </div>
            <p className="text-[11px] text-slate-400 flex items-center gap-1.5">
              <GitFork className="w-3.5 h-3.5" />
              {t('cfgTopologyHint')}
            </p>
          </section>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-3.5 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="text-[11px] text-rose-500 min-h-[1em]">{createError ?? problems[0] ?? ''}</div>
          <div className="flex items-center gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-semibold text-xs transition-colors"
            >
              {t('cancel')}
            </button>
            <button
              type="button"
              disabled={!canCreate || !!createdName || isCreating}
              onClick={handleCreate}
              className="px-5 py-2 rounded-xl text-white font-semibold text-xs flex items-center gap-2 transition-all bg-cyan-600 hover:bg-cyan-500 disabled:bg-slate-400 dark:disabled:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-60"
            >
              <Server className="w-3.5 h-3.5" />
              <span>{isCreating ? t('cfgCreating') : t('cfgCreateButton')}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
